name: Bug Report
description: Report a reproducible defect in Smart Clipping
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please provide enough detail to reproduce it.
  - type: input
    id: addon_version
    attributes:
      label: Addon version
      placeholder: "1.0.0"
    validations:
      required: true
  - type: input
    id: blender_version
    attributes:
      label: Blender version
      placeholder: "4.0.x"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "Windows 11 / Ubuntu 24.04 / macOS 14"
    validations:
      required: true
  - type: dropdown
    id: scope
    attributes:
      label: Target Scope at time of issue
      options:
        - SELF
        - SELECTED
        - VISIBLE
        - COLLECTION
    validations:
      required: true
  - type: input
    id: budget
    attributes:
      label: Max Vertex Budget
      placeholder: "50000"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Console logs
      description: Paste relevant Smart Clipping logs from Blender console.
      render: shell
    validations:
      required: false
